#patreon:            patreon_username
#open_collective:    open_collective_username
#ko_fi:              ko_fi_username
#tidelift:           tidelift_package_name
#community_bridge:   community_bridge_username
#liberapay:          liberapay_username
#issuehunt:          issuehunt_username
#otechie:            otechie_username
custom:             ["paypal.me/iamrohitchouhan"]
