[{
					"id":"8",
					"name":"AR",
					"full_name":"Assault Rifels",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/ar-gun.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/ar"
				},{
					"id":"13",
					"name":"LMG",
					"full_name":"Light Machine Guns",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/lmg.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/lmg"
				},{
					"id":"12",
					"name":"MR",
					"full_name":"Marksman Rifles",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/marksman-rifles.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/mr"
				},{
					"id":"4",
					"name":"MELEE",
					"full_name":"Melee",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/melee-item.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/melee"
				},{
					"id":"10",
					"name":"OTHER",
					"full_name":"Others",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/others.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/other"
				},{
					"id":"2",
					"name":"PISTOL",
					"full_name":"Pistols",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/pistol.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/pistol"
				},{
					"id":"6",
					"name":"SHOTGUN",
					"full_name":"Shotguns",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/shotgun-gun.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/shotgun"
				},{
					"id":"7",
					"name":"SNIPER",
					"full_name":"Sniper Rifels",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/sniper-gun.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/sniper"
				},{
					"id":"3",
					"name":"SMG",
					"full_name":"Sub Machine Guns",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/smg-gun.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/smg"
				},{
					"id":"5",
					"name":"THROWABLE",
					"full_name":"Throwable",
					"image":"https://raw.githubusercontent.com/pubgapi/v1/main/images/gun-category/throwable-item.png",
					"source":"https://raw.githubusercontent.com/pubgapi/v1/main/cat/throwable"
				}]